;* tools.msg
;*****************************************************************************
;* AS-Portierung                                                             *
;*                                                                           *
;* Stringdefinitionen, die alle AS-Tools brauchen                            *
;*****************************************************************************

Include header.msg

Message FormatErr1aMsg
 "Das Format der Datei ""
 "the format of file ""

Message FormatErr1bMsg
 "" ist fehlerhaft!"
 "" is invalid!"

Message FormatErr2Msg
 "Bitte "CH_ue"bersetzen Sie die Quelldatei neu!"
 "please reassemble the source file!"

Message IOErrAHeaderMsg
 "Bei Bearbeitung der Datei ""
 "the following error occured while processing ""
 
Message IOErrBHeaderMsg
 "" ist folgender Fehler aufgetreten:"
 "" :"

Message ErrMsgTerminating
 "Das Programm wird beendet!"
 "program terminated!"
